// demo/react/src/App.jsx
import { useRef, useEffect } from 'react'
import 'canvas-img'

export default function App() {
  const canvasRef = useRef(null)

  useEffect(() => {
    const ctx = canvasRef.current.getContext('2d')

    ctx.drawImageCORS('https://picsum.photos/400/300', 50, 50)
    ctx.drawImageCORS('https://picsum.photos/400/200', 500, 50, 200, 150)
    ctx.drawImageCORS(
      'https://picsum.photos/400/400',
      50, 50, 200, 150,
      50, 300, 200, 150
    )
  }, [])

  return <canvas ref={canvasRef} width={800} height={600} />
}

// demo/angular/src/app/app.component.ts
import { Component, AfterViewInit, ViewChild, ElementRef } from '@angular/core'
import 'canvas-img'

@Component({
  selector: 'app-root',
  standalone: true,
  template: '<canvas #canvas width="800" height="600"></canvas>',
})
export class AppComponent implements AfterViewInit {
  @ViewChild('canvas', { static: false }) canvasRef!: ElementRef<HTMLCanvasElement>

  ngAfterViewInit() {
    const ctx = this.canvasRef.nativeElement.getContext('2d')
    if (!ctx) return

    ctx.drawImageCORS('https://picsum.photos/400/300', 50, 50)
    ctx.drawImageCORS('https://picsum.photos/400/200', 500, 50, 200, 150)
    ctx.drawImageCORS(
      'https://picsum.photos/400/400',
      50, 50, 200, 150,
      50, 300, 200, 150
    )
  }
}
